language: python
python: 3.5

install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install pylint
  - pip install -r requirements.txt
  
script:
  - python setup.py nosetests
  - pylint diagonal_crop
